spring:
  application:
    name: backend

  profiles:
    active: dev

  mvc:
    static-path-pattern: /static/**
    problemdetails:
      enabled: true

  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: false

custom:
  jwt:
    secretKey: ${SECRET_KEY}
    expireTime: 15
