name: Java CI/CD Pipeline

on:
  push:
    branches: [ main, dev, feat/* ]
  pull_request:
    branches: [ main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: Backend

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: Backend

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: Backend/build/reports/tests/test/

    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: Backend/build/test-results/test/*.xml
